env:
  node: true
  es6: true
  jest: true
extends: [airbnb-base, "plugin:prettier/recommended", "plugin:jest/recommended"]
plugins: [import, babel, jest]
parser: babel-eslint
parserOptions:
  sourceType: module
  allowImportExportEverywhere: false
  parser: optionalChaining
  codeFrame: false
rules:
  arrow-body-style: [2, "as-needed"]
  arrow-spacing: 2
  camelcase: 1
  capitalized-comments: 2
  complexity: [2, 30]
  max-lines: [2, 50]
  max-depth: [2, 2]
  max-params: [2, 2]
  max-statements: [2, 7]
  max-statements-per-line: 2
  max-nested-callbacks: [2, 2]
  max-len: [1, code: 100]
  no-unused-vars: 2
  no-alert: 2
  no-caller: 2
  no-console: 1
  no-empty-function: 2
  no-else-return: 2
  no-extend-native: 2
  no-new-wrappers: 2
  no-script-url: 2
  no-throw-literal: 2
  no-void: 2
  no-with: 2
  no-trailing-spaces: 2
  no-duplicate-imports: 2
  no-var: 2
  no-eval: 2
  no-undef: 2
  no-undef-init: 2
  no-undefined: 2
  no-new-object: 2
  no-nested-ternary: 2
  no-useless-constructor: 2
  prefer-promise-reject-errors: 2
  prefer-rest-params: 2
  prefer-spread: 2
  quotes: [2, single]
  require-await: 2
  semi: [2, always]
  linebreak-style: [1, windows]
  no-plusplus: 2
